version: 0.2

phases:
  pre_build:
    commands:
      - rm -rf .git
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-west-2)
  build:
    commands:
       - echo Build started on `date`
       - echo Building the Docker image...
       - docker	build -t yo-image .
       - docker tag yo-image:latest 484387184102.dkr.ecr.us-west-2.amazonaws.com/yo-image:latest 
  post_build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker push 484387184102.dkr.ecr.us-west-2.amazonaws.com/yo-image:latest 
      - aws ecs update-service --cluster new --service --task-definition 1704:1 --desired-count 1
